### ISSUE TITLE
IOS :Could not find all required Titanium Modules

### ISSUE THREAD

**Issue by dzHamid** [kosso/TiAVPlayer#1]
Hello Sir,

First, thanks for this Module. 
I'm new in Titanium, i install this module but i had this error : 

[WARN] :   Could not find a valid Titanium module id=com.kosso.tiavplayer version=0.1.0.1 platform=iphone deploy-type=development
[ERROR] :  Could not find all required Titanium Modules:
[ERROR] :     id: com.kosso.tiavplayer   version: 0.1.0.1    platform: iphone

Thank you Sir

**Comment by kosso** [comment]
You have to build it. 
I'll upload a pre-built zip which you will then ned to install like all Titanium modules. 

Sorry for lack of documentation! ;)

**Comment by dzHamid** [comment]
i tried to build it, i also had errors.
i'm waiting for pre-built zip.

Thank you very much :D
